import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieConsentWrapper from "@/src/components/cookie/CookieConsentWrapper";
import { AppDataProvider } from "@/src/context/AppDataContext";
import TopNavbar from "@/src/components/navbar/TopNavbar";
import Footer from "@/src/components/footer/Footer";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNavbar />
        <AppDataProvider>{children}</AppDataProvider>
        <CookieConsentWrapper />
        <Footer />
      </body>
    </html>
  );
}
